services:
  api:
    container_name: esecustomers
    build:
      context: .
    ports:
      - "8083:8083"
    networks:
      - eseklugdorow

networks:
  eseklugdorow:
    name: eseklugdorow
    external: true